//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veritabani
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class giyimMagzasiDBEntities : DbContext
    {
        public giyimMagzasiDBEntities()
            : base("name=giyimMagzasiDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Beden> Beden { get; set; }
        public virtual DbSet<Kumas> Kumas { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<Musteri> Musteri { get; set; }
        public virtual DbSet<Renk> Renk { get; set; }
        public virtual DbSet<Siparisler> Siparisler { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Urun> Urun { get; set; }
        public virtual DbSet<Yonetici> Yonetici { get; set; }
        public virtual DbSet<Yorum> Yorum { get; set; }
    }
}
