//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparisler
    {
        public int siparis_id { get; set; }
        public Nullable<int> musteri_fk { get; set; }
        public Nullable<int> siparisTutarı { get; set; }
        public Nullable<int> urun_fk { get; set; }
        public string adres { get; set; }
    
        public virtual Musteri Musteri { get; set; }
        public virtual Urun Urun { get; set; }
    }
}
