//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urun()
        {
            this.Siparisler = new HashSet<Siparisler>();
        }
    
        public int urun_id { get; set; }
        public string urunAd { get; set; }
        public Nullable<int> urunKumasi_fk { get; set; }
        public Nullable<int> urunFiyat { get; set; }
        public Nullable<int> urunBeden_fk { get; set; }
        public Nullable<int> urunRenk_fk { get; set; }
    
        public virtual Beden Beden { get; set; }
        public virtual Kumas Kumas { get; set; }
        public virtual Renk Renk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Siparisler> Siparisler { get; set; }
    }
}
